# Generated by Django 4.1.3 on 2022-11-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='PoultryProduct',
        ),
    ]
