# Generated by Django 4.1.3 on 2022-11-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_product_poultryproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoultryProduct',
            new_name='Product',
        ),
    ]
