# Generated by Django 4.1.3 on 2022-11-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_customer_passwoord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullName',
            new_name='name',
        ),
    ]
