# Generated by Django 4.1.3 on 2022-11-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
