# Generated by Django 4.1.3 on 2022-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='User',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
