# Generated by Django 4.1.3 on 2022-11-23 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_rename_email_customerfeedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
