# Generated by Django 4.1.3 on 2022-11-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_customerfeedback_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerfeedback',
            old_name='button',
            new_name='paid',
        ),
    ]
