# Generated by Django 4.1.3 on 2022-11-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_rename_button_customerfeedback_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='paid',
        ),
    ]
